import "@/styles/global.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { AspectRatio } from "@/components/ui/aspect-ratio";

import MainLayout from "@/components/navigation/MainLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const className = [inter.className, "dark"].join(" ");
  return (
    <html lang="en">
      <body className={className}>
        <AspectRatio ratio={16 / 9} className="root overflow-hidden">
          <div className=" min-h-full flex-col justify-between py-[2vw] px-[4vw]">
            <MainLayout />
            {children}
          </div>
        </AspectRatio>
      </body>
    </html>
  );
}
